package kpi.ipt.labs.distributed.twophasecommit.service.impl;

import kpi.ipt.labs.distributed.twophasecommit.ConnectionInfo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public abstract class AbstractPgBookingService<T> {

    private final ConnectionInfo connInfo;

    public AbstractPgBookingService(ConnectionInfo connInfo) {
        this.connInfo = connInfo;
    }

    //TODO: checkup all exceptions
    protected int doBooking(T bookingEntity) throws SQLException {
        Connection connection = Utils.getTransactionalConnection(connInfo);

        try (PreparedStatement statement = Utils.withAutoGeneratedKeys(connection, getInsertQuery())) {
            setParameters(statement, bookingEntity);

            statement.executeUpdate();

            return Utils.extractGeneratedId(getIdColumnName(), statement);
        }
    }

    protected abstract String getInsertQuery();

    protected abstract String getIdColumnName();

    protected abstract void setParameters(PreparedStatement insertStmt, T bookingEntity) throws SQLException;
}
